site_name: GetDX Monorepo Service Identifier Action
repo_url: https://github.com/Kajabi/getdx-monorepo-service-identifier-action/
docs_dir: docs
theme:
    name: mkdocs
    highlightjs: true
    primary: light-blue
nav:
  - Intro: 'index.md'
plugins:
  - techdocs-core
